{
 "title": "Simplivity Cluster Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clusterName",
    "label": "Select Cluster Name",
    "query": "select \"name\" from \"simplivityCluster\""
   }
  ]
 },
 "panels": [
  {
   "title": "'$clusterName' Physical Capacity Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "Storage Utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityCluster",
     "query": "SELECT last(\"usedCapacity\") * 100 / (last(\"usedCapacity\") + last(\"freeCapacity\")) AS storageUtizaition FROM \"simplivityCluster\" WHERE (\"hostname\" = '$clusterName') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usedCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "DC-Cluster01" }
     ]
    }
   ]
  },
  {
   "title": "$clusterName Data reduction Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityCluster",
     "select": [
      [
       { "params": [ "reductRatio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reduction Ratio" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$clusterName$/" }
     ]
    }
   ]
  },
  {
   "title": "$clusterName Data dedupe Ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityCluster",
     "select": [
      [
       { "params": [ "dedupeRatio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reduction Ratio" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$clusterName$/" }
     ]
    }
   ]
  },
  {
   "title": "$clusterName Logical Capacity",
   "type": "graph",
   "description": "Cluster Logical Capacity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "TiB" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityCluster",
     "query": "SELECT last(\"vmData\") AS \"VM Data\", \"localBackup\" AS \"Local Backup\", \"remoteBackup\" AS \"Remote Backup\" FROM \"simplivityCluster\" WHERE (\"hostname\" = '$clusterName') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "vmData" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VM Data" ], "type": "alias" }
      ],
      [
       { "params": [ "localBackup" ], "type": "field" },
       { "params": [ "Local Backup" ], "type": "alias" }
      ],
      [
       { "params": [ "remoteBackup" ], "type": "field" },
       { "params": [ "Remote Backup" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "DC-Cluster01" }
     ]
    }
   ]
  },
  {
   "title": "$clusterName Data CompressionRatio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityCluster",
     "select": [
      [
       { "params": [ "compressRatio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reduction Ratio" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$clusterName$/" }
     ]
    }
   ]
  }
 ]
}