{
 "title": "Simplivity Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Used Physical Capacity",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "simplivityNode",
     "query": "SELECT last(\"usedCapacity\") * 100 / ( last(\"freeCapacity\") +  last(\"usedCapacity\")) AS storageUtilization FROM \"simplivityNode\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" fill(previous)",
     "select": [
      [
       { "params": [ "freeCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "usedCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Simplivity Node Data Reduction Ratio",
   "type": "gauge",
   "description": "Simplivity Node Data Reduction Ratio",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "simplivityNode",
     "select": [
      [
       { "params": [ "reductRatio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Simplivity Node Physical Capacity Trend (TiB)",
   "type": "graph",
   "description": "Simplivity Physical Capacity Trend per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "TiB" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "simplivityNode",
     "select": [
      [
       { "params": [ "usedCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Simplivity Node Data Deduplication Ratio",
   "type": "gauge",
   "description": "Simplivity Node Data Deduplication Ratio",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "simplivityNode",
     "select": [
      [
       { "params": [ "dedupeRatio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Simplivity Node Data Compression Ratio",
   "type": "gauge",
   "description": "Simplivity Node Data Compression Ratio",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "simplivityNode",
     "select": [
      [
       { "params": [ "compressRatio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Simplivity Node Logical Capacity Trend (TiB)",
   "type": "graph",
   "description": "Simplivity Logical Capacity Trend per Node",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "TiB" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "simplivityNode",
     "query": "SELECT last(\"vmData\") + last(\"localBackup\") + last(\"remoteBackup\") AS logocalData FROM \"simplivityNode\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "usedCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Simplivity Node Logical VM Data Trend (TiB)",
   "type": "graph",
   "description": "Simplivity Node Logical VM Data Trend (TiB)",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "TiB" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "simplivityNode",
     "query": "SELECT last(\"remoteBackup\") FROM \"simplivityNode\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "vmData" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Simplivity Node Logical Local Backup Trend (TiB)",
   "type": "graph",
   "description": "Simplivity Node Logical Local Backup Trend (TiB)",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "TiB" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "simplivityNode",
     "query": "SELECT last(\"remoteBackup\") FROM \"simplivityNode\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "localBackup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Simplivity Node Logical Remote Backup Trend (TiB)",
   "type": "graph",
   "description": "Simplivity Node Logical Remote  Backup Trend (TiB)",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "TiB" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "simplivityNode",
     "query": "SELECT last(\"remoteBackup\") FROM \"simplivityNode\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "remoteBackup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}