{
 "title": "Simplivity BackUp Dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Total Backup Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Backups" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityBackup",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backup Retention days histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "No. of Backups" }
   ],
   "targets": [
    {
     "alias": "No of backups",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityBackup",
     "select": [
      [
       { "params": [ "retentionDay" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Retention" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Replication Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 0 },
   "format": "Mbits",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Replication Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityBackup",
     "query": "SELECT last(\"sent\")  / last(\"sent_duration\") * 8 / 1000000 AS Bandwidth FROM \"simplivityBackup\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sent_duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Replication Effiency (x)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityBackup",
     "query": "SELECT last(\"size\")/last(\"sent\")  AS ReplicationEffiency FROM \"simplivityBackup\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Replication Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 4 },
   "format": "Mbits",
   "valueName": "max",
   "targets": [
    {
     "alias": "Replication Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityBackup",
     "query": "SELECT last(\"sent\")  / last(\"sent_duration\") * 8 / 1000000 AS Bandwidth FROM \"simplivityBackup\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sent_duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Replication Effiency (x)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityBackup",
     "query": "SELECT last(\"size\")/last(\"sent\")  AS ReplicationEffiency FROM \"simplivityBackup\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historical backup status created time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "BackUps" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "simplivityBackup",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}